### PR TITLE
feat: add multi route colors 🎉

### LINKED ISSUE #57: Route differentiation in multi-route display
For the multi-route displaying feature to be complete, in terms of visualization, additional changes are needed

- **colour markers**, vehicles belonging to a route will be rendered with a specific colour
- **itinerary** - to indicate the endpoints of the routes
- **vehicle tag** - a label next to the vehicle marker, linking it to a route

Example
image

Notes on colours and constraints:
- Use colours that are "far" from each other and are easily distinguishable, this [scheme will do](http://colorbrewer2.org/#type=qualitative&scheme=Set1&n=4). image
- Do not display more than 4 routes at once. First of all, 4 should be enough for anyone, and second - there's no set of 5+ colours that are different enough to be meaningfully differentiated with confidence
- Do not rely on colour as the sole channel to convey the message. Some people are colour blind, and although the chosen schema should address that, writing the actual route name will be an unambiguous answer to the question "what route am I looking at?" (that's what the vehicle tags are for).
- Each colour comes with an accompanying, slightly lighter version, used for the route segments. Here you can see a "blue" for the marker and a "lighter blue" for the route:
image

### PR DESCRIPTION
**Pull request by dasshield**
closes #57, with some 'inaccuracies':

1. Random colors instead of hardcoded ones;
2. There's already a route number within a marker;
3. Segments have ultra- slightly lighter color version;
4. 'Do not display more than 4 routes at once' constraints aren't added.

### CODE REVIEW

**Comment by ralienpp** [comment]
Wow, thanks! It looks much better and is a step in the right direction. However, one may get unlucky and the random colours will look very similar, like in this example that just happened to me:

image



I believe we can find a hybrid approach:
1. the first N routes use predefined colours that were chosen to provide good contrast.
2. anything above that will use random colours, like in the current draft implementation.

Of course, it is possible that the newly generated colours will look a lot like some of the existing one, but when when one goes beyond N, they're probably not a regular user and we cannot make them happy unless we understand the motivation.

**Comment by dasshield** [comment]
I've added 5 predefined colors:
image

Generally, while there're ~30 routes it's even possible to hard-code a color for each route number, but it's not so interesting 🌚

**Comment by ralienpp** [comment]
Displaying 30 routes at once will clutter the UI a lot, and besides that - the human eye won't be able to distinguish the small variations in colour, due to our physiology. That's why the original idea was to limit the number of selected routes to N=5.

However, you are right - we can push this bound a bit further by leveraging this palette: https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=12

You'll notice that colours 1,2,3,4,5 are the same as before, but there are 7 additional ones which still provide good contrast. Their only downside is that unlike the first 5, which are colour-blind safe, these remaining ones will be challenging for colour-blind people, or those who are otherwise visually impaired. 

image


So, I think that if we extend the list of 5 hardcoded colours with the new 7 entries - we'll have an aesthetically pleasing and usable map. Whoever goes beyond 12 routes at once - they're in uncharted territories :-)

**Comment by ralienpp** [comment]
I tinkered with it a bit after your last commit and there is one last quirk that I noticed in the way colours are iterated through.

1. Go to the route selection screen
2. Enable a route -> observe how it gets colour C1
3. Disable it and enable it back -> it gets C2
4. Repeat the last step a bunch of times and observe How we go to C3, C4... C12 - and then we're off into the "random colour" territory.

Once a colour is "consumed", it won't be reused again, even if we only have one active route. Ideally, a discarded colour should go back into the pool, such that it is available again.

**Comment by dasshield** [comment]
Updated 💪

**Comment by ralienpp** [comment]
I gave it a try, there's just a blank page. Having looked under the hood, I see this:
image

**Comment by dasshield** [comment]
I apologize, I got a bit wrong in logic due to a clean-up before a commit :'(

**Comment by ralienpp** [comment]
No worries! It looks good now and I'm quite happy with how it behaves. This is a major usability improvement, thanks for making it happen!

If @iamandrewluca is OK with the implementation details, then I have nothing else to add.

**Comment by iamandrewluca** [comment]
I'll make a full review in the evening

**Comment by iamandrewluca** [comment]
LGTM

**Pull request merged**
